# Generated by Django 5.1.1 on 2024-09-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
