# Generated by Django 5.1.1 on 2024-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
